### ISSUE TITLE
修改建议

### ISSUE THREAD

**Issue by aispin** [o2team/cases#1]
1. 主体内容设置最大宽度

  现在的fluid布局在大屏幕下（如imac）因为列数太多看起来很累，建议按照aotu.io来做调整，主体最大宽度1600或1490

2. 保留aotu.io官网的导航和banner

  保留aotu.io官网的导航和banner，同时在主导航上「资讯」后面新增「H5案例」

**Comment by JChehe** [comment]
@mamboer 已根据『建议』修改。
