### ISSUE TITLE
请教个细节问题：点击不同的卡片，a链接都是在同一个浏览器标签页里打开，是怎么做到的？

### ISSUE THREAD

**Issue by Evermenot** [o2team/cases#3]

**Comment by Evermenot** [comment]
https://cases.aotu.io/index.html

**Comment by chuyik** [comment]
因为所有 a 标签都设置了 `target="__blank"`，指定用同一个窗口打开，这个窗口名字就叫做 `__blank`。

**Comment by Evermenot** [comment]
谢谢回复
target="__blank"不是在新建的窗口里打开吗？
可以指点在同一个窗口打开？
